version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    env_file: app/.env
  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    env_file: db/.env

    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro